Repository jasonn0118/Beezly, pull requests merged in 2025-07, with the labels that each got.

#107 feat(utils): add Supabase storage utility functions for receipt and p…
  apps/api/src/app.module.ts
  apps/packages/utils/package.json
  apps/packages/utils/src/index.ts
  apps/packages/utils/src/storage.util.ts
  apps/packages/utils/src/supabase.client.ts
  package.json
  pnpm-lock.yaml
  tsconfig.json
Labels: enhancement

#113 feat(api): update dependencies and enhance environment configuration
  apps/api/.env.example
  apps/api/README.md
  apps/api/package.json
  apps/api/src/app.module.ts
  apps/api/src/main.ts
  apps/api/src/ocr/README.md
  apps/api/src/ocr/dto/process-receipt.dto.ts
  apps/api/src/ocr/ocr.controller.ts
  apps/api/src/ocr/ocr.module.ts
  apps/api/src/ocr/ocr.service.spec.ts
  apps/api/src/ocr/ocr.service.ts
  apps/packages/utils/src/storage.util.ts
  apps/packages/utils/src/supabase.client.ts
  pnpm-lock.yaml
Labels: documentation, enhancement

#121 chore(deps): update package dependencies and add multer override
  apps/api/package.json
  package.json
  pnpm-lock.yaml
Labels: bug, enhancement

#125 feat(api): enhance barcode and category management features
  apps/api/jest.config.ts
  apps/api/package.json
  apps/api/src/app.controller.ts
  apps/api/src/app.module.ts
  apps/api/src/auth/auth.controller.ts
  apps/api/src/barcode/barcode.controller.spec.ts
  apps/api/src/barcode/barcode.controller.ts
  apps/api/src/barcode/barcode.service.ts
  apps/api/src/barcode/dto/barcode-lookup.dto.ts
  apps/api/src/barcode/dto/product-response.dto.ts
  apps/api/src/category/category.controller.ts
  apps/api/src/entities/product.entity.ts
  apps/api/src/main.ts
  apps/api/src/migrations/1752867138250-AddBarcodeTypeToProduct.ts
  apps/api/src/ocr/ocr.controller.ts
  apps/api/test/jest-e2e.json
  apps/api/tsconfig.json
  apps/demo/package.json
  apps/mobile/package.json
  apps/packages/types/dto/barcode.ts
  apps/packages/types/dto/index.ts
  apps/packages/types/dto/product.ts
  apps/packages/types/package.json
  apps/packages/types/tsconfig.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  turbo.json
Labels: documentation, enhancement

#127 fix(product): resolve API error by updating Product DTO and related objects
  apps/api/src/product/product.service.spec.ts
  apps/api/src/product/product.service.ts
  apps/api/src/receipt/receipt.service.ts
  apps/packages/types/dto/product.ts
Labels: bug

#126 feat(api): add axios dependency and configure CORS settings
  .github/workflows/ci-cd.yml
  .github/workflows/database-migration-check.yml
  apps/api/MIGRATION_GUIDE.md
  apps/api/PORTS.md
  apps/api/README.md
  apps/api/package.json
  apps/api/src/app.module.ts
  apps/api/src/database-health-check.service.ts
  apps/api/src/main.ts
  apps/api/src/supabase-migration-sync.ts
  apps/mobile/package.json
  apps/mobile/src/services/api.ts
  apps/mobile/src/services/authService.ts
  apps/mobile/src/services/index.ts
  apps/mobile/src/services/productService.ts
  apps/mobile/src/services/receiptService.ts
  apps/web/package.json
  apps/web/src/services/api.ts
  apps/web/src/services/authService.ts
  apps/web/src/services/index.ts
  apps/web/src/services/productService.ts
  apps/web/src/services/receiptService.ts
  package.json
  pnpm-lock.yaml
  turbo.json
Labels: documentation, enhancement

#129 feat(barcode): include category and image_url in product response
  apps/api/src/barcode/barcode.service.ts
  apps/api/src/barcode/dto/product-response.dto.ts
Labels: enhancement

#138 feat(setup): enhance developer setup and environment configuration
  .github/workflows/ci-cd.yml
  .gitignore
  DEVELOPER_SETUP.md
  README.md
  apps/api/.env.example
  apps/api/.env.local.example
  apps/api/.env.production.example
  apps/api/.env.staging.example
  apps/api/.env.test
  apps/api/.env.test.example
  apps/api/.gitignore
  apps/api/DATABASE_SETUP.md
  apps/api/README.md
  apps/api/package.json
  apps/api/scripts/dev-auto.ts
  apps/api/scripts/dev-setup.ts
  apps/api/scripts/dev-with-setup.sh
  apps/api/src/config/data-source.config.ts
  apps/api/src/migrations/1700000000000-InitialSchema.ts
  apps/api/src/seeds/clear.ts
  apps/api/src/seeds/data/badges.seed.ts
  apps/api/src/seeds/data/categories.seed.ts
  apps/api/src/seeds/data/products.seed.ts
  apps/api/src/seeds/data/products.seed.ts.backup
  apps/api/src/seeds/data/score-types.seed.ts
  apps/api/src/seeds/data/stores.seed.ts
  apps/api/src/seeds/data/users.seed.ts
  apps/api/src/seeds/seed.ts
  apps/mobile/.env.example
  apps/mobile/.env.production.example
  apps/mobile/.env.staging.example
  apps/mobile/.gitignore
  apps/web/.env.local.example
  apps/web/.env.production.example
  apps/web/.env.staging.example
  apps/web/.gitignore
  package.json
  pnpm-lock.yaml
Labels: bug, documentation, enhancement

#139 feat(ci-cd): enhance environment-specific configurations and logging
  .github/workflows/ci-cd.yml
Labels: documentation, enhancement

#145 feat(ci-cd): unify environment configurations and enhance secret management
  .github/workflows/ci-cd.yml
  apps/api/DATABASE_SETUP.md
Labels: enhancement

#147 feat(api): integrate Price module and enhance Category service
  apps/api/src/app.module.ts
  apps/api/src/category/category.module.ts
  apps/api/src/category/category.service.ts
  apps/api/src/price/price.controller.ts
  apps/api/src/price/price.module.ts
  apps/api/src/price/price.service.ts
  apps/api/src/product/dto/mobile-product-create.dto.ts
  apps/api/src/product/product.controller.ts
  apps/api/src/product/product.module.ts
  apps/api/src/product/product.service.spec.ts
  apps/api/src/product/product.service.ts
  apps/packages/types/dto/category.ts
Labels: documentation, enhancement

#151 feat(migration): enhance category and product schema migration with existence checks
  apps/api/src/migrations/1753316790537-Migration.ts
Labels: bug, enhancement

#152 Feature/search by product name
  apps/api/src/barcode/barcode.controller.spec.ts
  apps/api/src/barcode/barcode.controller.ts
  apps/api/src/barcode/barcode.service.spec.ts
  apps/api/src/barcode/barcode.service.ts
  apps/api/src/barcode/dto/barcode-lookup.dto.ts
  apps/api/src/product/dto/mobile-product-create.dto.ts
  apps/api/src/product/dto/product-search-response.dto.ts
  apps/api/src/product/product.controller.ts
  apps/api/src/product/product.service.ts
  apps/api/test/barcode.e2e-spec.ts
  apps/api/test/product-search.e2e-spec.ts
  apps/packages/types/dto/product.ts
Labels: enhancement

#150 Feature/product normalization 2
  apps/api/.env.local.example
  apps/api/.env.production.example
  apps/api/.env.staging.example
  apps/api/.env.test.example
  apps/api/PORTS.md
  apps/api/docs/MIGRATION_GUIDE.md
  apps/api/package.json
  apps/api/src/entities/normalized-product.entity.ts
  apps/api/src/entities/price.entity.ts
  apps/api/src/migrations/1753160046810-AddProductNormalizationFields.ts
  apps/api/src/migrations/1753161400000-AddDiscountFieldsToPrice.ts
  apps/api/src/migrations/1753246984782-AddPgvectorExtension.ts
  apps/api/src/ocr/README.md
  apps/api/src/ocr/dto/process-receipt.dto.ts
  apps/api/src/ocr/ocr-azure.service.ts
  apps/api/src/ocr/ocr.controller.ts
  apps/api/src/ocr/ocr.module.ts
  apps/api/src/ocr/ocr.service.spec.ts
  apps/api/src/ocr/ocr.service.ts
  apps/api/src/product/openai.service.ts
  apps/api/src/product/product-normalization.service.spec.ts
  apps/api/src/product/product-normalization.service.ts
  apps/api/src/product/product.module.ts
  apps/api/src/product/store-patterns.config.ts
  apps/api/src/product/vector-embedding.service.ts
  apps/api/src/receipt/dto/test-normalization-response.dto.ts
  apps/api/src/receipt/dto/upload-receipt-response.dto.ts
  apps/api/src/receipt/receipt.controller.ts
  apps/api/src/receipt/receipt.service.spec.ts
  apps/api/src/receipt/receipt.service.ts
  apps/api/src/seeds/data/products.seed.ts.backup
  apps/api/src/seeds/data/stores.seed.ts
  apps/packages/types/dto/product.ts
  pnpm-lock.yaml
Labels: enhancement

#155 feat(product): add product_sk to ProductSearchResponseDto and update …
  apps/api/src/product/dto/product-search-response.dto.ts
  apps/api/src/product/product.service.ts
  apps/api/test/product-search.e2e-spec.ts
Labels: enhancement

#156 fix(dev-setup): improve database existence check and error handling
  apps/api/scripts/dev-setup.ts
Labels: bug

#184 Feature/relation among the product normalized procduct and price
  README.md
  apps/api/README.md
  apps/api/src/app.module.ts
  apps/api/src/config/data-source.config.ts
  apps/api/src/entities/index.ts
  apps/api/src/entities/normalized-product.entity.ts
  apps/api/src/entities/receipt-item-normalization.entity.ts
  apps/api/src/entities/unprocessed-product.entity.ts
  apps/api/src/migrations/1753512220079-AddProductLinkingToNormalizedProduct.ts
  apps/api/src/migrations/1753612000000-AddUnprocessedProductTable.ts
  apps/api/src/migrations/1753713000000-AddPgTrgmExtension.ts
  apps/api/src/migrations/1753750994708-DropDuplicateTrgmIndex.ts
  apps/api/src/ocr/ocr-azure.service.ts
  apps/api/src/ocr/ocr.controller.ts
  apps/api/src/ocr/ocr.module.ts
  apps/api/src/ocr/ocr.service.spec.ts
  apps/api/src/ocr/ocr.service.ts
  apps/api/src/product/dto/product-selection.dto.ts
  apps/api/src/product/dto/receipt-confirmation.dto.ts
  apps/api/src/product/product-confirmation.service.ts
  apps/api/src/product/product-linking.service.ts
  apps/api/src/product/product-normalization.service.ts
  apps/api/src/product/product-selection.service.spec.ts
  apps/api/src/product/product-selection.service.ts
  apps/api/src/product/product.controller.ts
  apps/api/src/product/product.module.ts
  apps/api/src/product/product.service.ts
  apps/api/src/product/receipt-price-integration.service.ts
  apps/api/src/product/unmatched-product.service.ts
  apps/api/src/product/unprocessed-product.service.ts
  apps/api/src/receipt/receipt.service.ts
  apps/api/test/product-search.e2e-spec.ts
Labels: documentation, enhancement

#186 feat(docs): expand README with detailed receipt processing workflow a…
  apps/api/README.md
Labels: documentation

#187 Feature/relation among the product normalized procduct and price
  apps/api/src/entities/normalized-product.entity.ts
  apps/api/src/entities/receipt-item-normalization.entity.ts
  apps/api/src/migrations/1753909203198-AddFinalPriceToReceiptItemNormalization.ts
  apps/api/src/migrations/1753911308408-FixLinkedProductSkTypeToUuid.ts
  apps/api/src/migrations/1753912800000-FixEmbeddingColumnType.ts
  apps/api/src/ocr/ocr-azure.service.ts
  apps/api/src/product/enhanced-receipt-linking.service.ts
  apps/api/src/product/product.controller.ts
  apps/api/src/product/product.module.ts
  apps/api/src/product/receipt-price-integration.service.ts
  apps/api/src/product/receipt-workflow-integration.service.ts
  apps/api/src/store/store.service.ts
  apps/api/test/product-search.e2e-spec.ts
Labels: documentation, enhancement

#189 Feature/barcode product price and store relationship
  apps/api/src/barcode/barcode.module.ts
  apps/api/src/barcode/barcode.service.ts
  apps/api/src/barcode/dto/add-product-price.dto.ts
  apps/api/src/barcode/dto/enhanced-product-response.dto.ts
  apps/api/src/price/price.service.ts
  apps/api/src/product/dto/mobile-product-create.dto.ts
  apps/api/src/product/product.controller.ts
  apps/api/src/product/product.service.ts
Labels: enhancement

#190 feat(category): enhance category management with new endpoints
  apps/api/src/category/category.controller.ts
  apps/api/src/category/category.service.ts
  apps/api/src/category/dto/category-hierarchy.dto.ts
  apps/api/src/category/dto/create-category.dto.ts
  apps/api/src/category/dto/index.ts
Labels: bug, enhancement
